const {
  screen,
  cleanUp,
  fireEvent,
  createEvent,
  waitFor,
  waitForElementToBeRemoved,
  within,
  getRoles,
  logRoles,
  isInaccessible,
  queries,
  queryHelpers,
  buildQueries,
  getNodeText,
  act,
  render,
  renderHook,
  prettyDOM,
  configure,
} = require("@testing-library/react");

const userEvent = require("@testing-library/user-event");

// We need to import and register custom Jest matchers until it
// will be added to jest configuration generated by uuAppDevkit
require("@testing-library/jest-dom");

module.exports = {
  screen,
  cleanUp,
  fireEvent,
  createEvent,
  waitFor,
  waitForElementToBeRemoved,
  within,
  getRoles,
  logRoles,
  isInaccessible,
  queries,
  queryHelpers,
  buildQueries,
  getNodeText,
  act,
  render,
  renderHook,
  prettyDOM,
  configure,
  userEvent: userEvent.default,
};
